services:
  server:
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
    ports:
        - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
